AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: >
  Appsync api example for subscription based communication

Resources:
  RequestProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: ./lambda
      Handler: processor.handler
  GraphqlApi:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: test-api
      Auth:
        Type: API_KEY
        Additional:
          - Type: AWS_IAM
      SchemaUri: schema.graphql
      DataSources:
        Lambda:
          RequestProcessor:
            Name: RequestProcessor
            FunctionArn: !GetAtt RequestProcessor.Arn
            ServiceRoleArn: !GetAtt RequestProcessorRole.Arn
            Description: "Example processor Lambda"
      Functions:
        processLambda:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          CodeUri: ./resolvers/submitRequestForProcessing.js
          DataSource: RequestProcessor
      Resolvers:
        Mutation:
          submitForProcessing:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - processLambda

  NoneTypeDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Type: NONE
      Name: NoneTypeDataSource
      Description: An empty data source. Used for subscription resolvers that do not require a data source.

  OnSuccessfulResultResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphqlApi.ApiId
      TypeName: Subscription
      FieldName: onSuccessfulResult
      Kind: UNIT
      CodeS3Location: ./resolvers/onSuccessfulResult.js
      DataSourceName: !GetAtt NoneTypeDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0

  EmitSuccessfulResultResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphqlApi.ApiId
      TypeName: Mutation
      FieldName: emitSuccessfulResult
      Kind: UNIT
      CodeS3Location: ./resolvers/emitSuccessfulResult.js
      DataSourceName: !GetAtt NoneTypeDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
